### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Captain-Kirkie** [garanda21/vapor-qrencode#1]
Hello, 

We may be interested in using this QR Code generator in other projects. There is no license associated with vapor-qrencode. 

Hoping to figure out what kind of licensing you are using for this project.

Thanks!

**Comment by garanda21** [comment]
> Hello,
> 
> We may be interested in using this QR Code generator in other projects. There is no license associated with vapor-qrencode.
> 
> Hoping to figure out what kind of licensing you are using for this project.
> 
> Thanks!

Hello, 

I've just added a new commit: e9a214d49c3e6a7972fd3c7d245bc87dd86dba91 that include **GNU GPLv3** license. Please let me know if you have more questions.
